# Generated by Django 5.1.5 on 2025-01-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
