# Generated by Django 5.1.5 on 2025-01-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_delete_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('Destination', 'Destination'), ('Indoor', 'Indoor')], max_length=20)),
                ('location_details', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('food_options', models.BooleanField(default=False)),
                ('advice', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Net Banking', 'Net Banking')], max_length=20)),
                ('advance_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
