# Generated by Django 5.1.5 on 2025-03-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_booking_payment_status_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
    ]
